[package]
name = "wzsh"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"

[dependencies]
failure = "0.1"
lazy_static = "1.3"
libc = "0.2"
rustyline = "3.0"
shlex = { path = "shlex" }
shell_lexer = { path = "shell_lexer" }
shell_parser = { path = "shell_parser" }
structopt = "0.2"

[dev-dependencies]
pretty_assertions = "0.6"

[workspace]
