name: windows

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [vs2017-win2016]
        rust_toolchain: [stable]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      shell: cmd
      run: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -yv --default-toolchain ${{ matrix.rust_toolchain }}
          rustup update ${{ matrix.rust_toolchain }}
    - name: Show versions
      shell: cmd
      run: |
        set path "%USERPROFILE%\.cargo\bin;%PATH"
        rustc -V
        cargo -V
    - name: Check formatting
      if: matrix.rust_toolchain == 'stable'
      shell: cmd
      run: |
        set path "%USERPROFILE%\.cargo\bin;%PATH"
        rustup component add rustfmt
        cargo fmt --all -- --check
    - name: Build
      shell: cmd
      run: |
        set path "%USERPROFILE%\.cargo\bin;%PATH"
        cargo build --all --release
    - name: Test
      shell: cmd
      run: |
        set path "%USERPROFILE%\.cargo\bin;%PATH"
        cargo test --all
    - name: Move Windows Package
      shell: bash
      run: |
        mkdir pkg_
        mv target/release/*.exe pkg_
    - uses: actions/upload-artifact@master
      with:
        name: windows
        path: pkg_
